"""add academic models

Revision ID: fb503ebdb8a1
Revises: 765550d5415f
Create Date: 2026-09-05 00:48:40.859990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb503ebdb8a1'
down_revision: Union[str, Sequence[str], None] = '765550d5415f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('qualifying_threshold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_scale', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tee_pass_mark', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('top_s_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_policies_active'), 'grade_policies', ['active'], unique=False)
    op.create_index(op.f('ix_grade_policies_id'), 'grade_policies', ['id'], unique=False)
    op.create_table('grade_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('minimum_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('maximum_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade_point', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['grade_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_bands_id'), 'grade_bands', ['id'], unique=False)
    op.create_index(op.f('ix_grade_bands_policy_id'), 'grade_bands', ['policy_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assessment_type', sa.Enum('CAT1', 'CAT2', 'TEE', 'INTERNAL', 'OTHER', name='assessmenttype'), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'LOCKED', 'FINALIZED', name='assessmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_academic_year'), 'assessments', ['academic_year'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_section_id'), 'assessments', ['section_id'], unique=False)
    op.create_index(op.f('ix_assessments_semester'), 'assessments', ['semester'], unique=False)
    op.create_index(op.f('ix_assessments_subject_id'), 'assessments', ['subject_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_assessment_student')
    )
    op.create_index(op.f('ix_marks_assessment_id'), 'marks', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_marks_entered_by'), 'marks', ['entered_by'], unique=False)
    op.create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_table('semester_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_results_academic_year'), 'semester_results', ['academic_year'], unique=False)
    op.create_index(op.f('ix_semester_results_id'), 'semester_results', ['id'], unique=False)
    op.create_index(op.f('ix_semester_results_semester'), 'semester_results', ['semester'], unique=False)
    op.create_index(op.f('ix_semester_results_status'), 'semester_results', ['status'], unique=False)
    op.create_index(op.f('ix_semester_results_student_id'), 'semester_results', ['student_id'], unique=False)
    op.create_table('student_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('raw_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tee_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('grade_point', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'REVIEWED', 'FINALIZED', name='resultstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['grade_policies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_results_academic_year'), 'student_results', ['academic_year'], unique=False)
    op.create_index(op.f('ix_student_results_grade'), 'student_results', ['grade'], unique=False)
    op.create_index(op.f('ix_student_results_id'), 'student_results', ['id'], unique=False)
    op.create_index(op.f('ix_student_results_policy_id'), 'student_results', ['policy_id'], unique=False)
    op.create_index(op.f('ix_student_results_semester'), 'student_results', ['semester'], unique=False)
    op.create_index(op.f('ix_student_results_status'), 'student_results', ['status'], unique=False)
    op.create_index(op.f('ix_student_results_student_id'), 'student_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_results_subject_id'), 'student_results', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_results_subject_id'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_student_id'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_status'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_semester'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_policy_id'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_id'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_grade'), table_name='student_results')
    op.drop_index(op.f('ix_student_results_academic_year'), table_name='student_results')
    op.drop_table('student_results')
    op.drop_index(op.f('ix_semester_results_student_id'), table_name='semester_results')
    op.drop_index(op.f('ix_semester_results_status'), table_name='semester_results')
    op.drop_index(op.f('ix_semester_results_semester'), table_name='semester_results')
    op.drop_index(op.f('ix_semester_results_id'), table_name='semester_results')
    op.drop_index(op.f('ix_semester_results_academic_year'), table_name='semester_results')
    op.drop_table('semester_results')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_entered_by'), table_name='marks')
    op.drop_index(op.f('ix_marks_assessment_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_assessments_subject_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_semester'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_section_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_academic_year'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_grade_bands_policy_id'), table_name='grade_bands')
    op.drop_index(op.f('ix_grade_bands_id'), table_name='grade_bands')
    op.drop_table('grade_bands')
    op.drop_index(op.f('ix_grade_policies_id'), table_name='grade_policies')
    op.drop_index(op.f('ix_grade_policies_active'), table_name='grade_policies')
    op.drop_table('grade_policies')
    # ### end Alembic commands ###
